# Generated by Django 3.2.3 on 2021-06-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
