# Generated by Django 3.2.3 on 2021-06-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_task_completed_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='completed',
        ),
    ]
